---
version: '3'
services:
  # currently we don't use named volumes or mapped volumes to ease adoption
  # one may want to change this in production, left as an exercise for the 
  # sysadmin
  workspace-db:
    image: mongo
    container_name: workspace-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=keklolxd
      - MONGO_INITDB_ROOT_PASSWORD=lolkekxd
  workspace:
    build: ./Workspace-Management
    container_name: workspace
    environment:
      - PORT=80
      - DATABASE=workspace_management
      - DATABASE_IP=workspace-db
      - DATABASE_USER=keklolxd
      - DATABASE_PASS=lolkekxd
      - MODEL_MANAGEMENT_HOST=model
      - MODEL_MANAGEMENT_PORT=80
      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

  model-db:
    image: mongo
    container_name: model-db
    restart: always
  model:
    build: ./Model-Management
    container_name: model
    environment:
      - PORT=80 
      - DATABASE_NAME=model_management
      - DATABASE_URI=mongodb://model-db/
      - WORKSPACE_MANAGEMENT_IP_PORT=http://workspace
      - AUTH_SECRET=${AUTHENTICATION_SECRET}

  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kekauthxd
      - MONGO_INITDB_ROOT_PASSWORD=authkekxd
  auth:
    build: ./Authentication
    container_name: auth
    environment:
      - PORT=80

      - DATABASE_IP=auth-db
      - DATABASE_USER=kekauthxd
      - DATABASE_PASS=authkekxd
      - DATABASE=authentication

      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  client:
    build: ./client
    container_name: client
    environment:
      - REACT_APP_BASE_URL=${BASE_URL}
    # ports:
    #   - 8080:80

  proxy:
    image: nginx
    container_name: proxy
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
    - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    - ./snippets:/etc/nginx/snippets
    - ./dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
    - 8443:443
