---
version: '3'
volumes:
  workspace_vol:
  auth_vol:
  model_vol:
services:
  workspace-db:
    image: mongo
    container_name: workspace-db
    restart: always
    volumes:
      - workspace_vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${WORKSPACE_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${WORKSPACE_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${WORKSPACE_DB_NAME}
  model-db:
    image: mongo
    container_name: model-db
    restart: always
    volumes:
      - model_vol:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MODEL_DB_NAME}
  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    volumes:
      - auth_vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AUTH_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${AUTH_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${AUTH_DB_NAME}

  workspace:
    build: ./Workspace-Management
    container_name: workspace
    network_mode: host
    environment:
      - PORT=11140

      - DATABASE_IP=workspace-db
      - DATABASE_PORT=27017
      - DATABASE=${WORKSPACE_DB_NAME}
      - DATABASE_USER=${WORKSPACE_DB_USERNAME}
      - DATABASE_PASS=${WORKSPACE_DB_PASSWORD}

      - MODEL_MANAGEMENT_HOST=localhost
      - MODEL_MANAGEMENT_PORT=11150
      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

  model:
    build: ./Model-Management
    container_name: model
    network_mode: host
    environment:
      - PORT=11150

      - DATABASE_NAME=${MODEL_DB_NAME}
      - DATABASE_PORT=27017
      - DATABASE_URI=mongodb://model-db/

      - WORKSPACE_MANAGEMENT_IP_PORT=http://localhost:11140
      - AUTH_SECRET=${AUTHENTICATION_SECRET}

  auth:
    build: ./Authentication
    container_name: auth
    network_mode: host
    environment:
      - PORT=11160

      - DATABASE=${AUTH_DB_NAME}
      - DATABASE_IP=auth-db
      - DATABASE_USER=${AUTH_DB_USERNAME}
      - DATABASE_PASS=${AUTH_DB_PASSWORD}
      - DATABASE_PORT=27017

      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  client:
    build: ./client
    container_name: client
    network_mode: host
    # environment:
    #   - PORT=80
    #   - BASE_URL=https://edge-ml.dmz.teco.edu/