---
version: '3'
volumes:
  workspace_vol:
  auth_vol:
  model_vol:
services:
  workspace-db:
    image: mongo
    container_name: workspace-db
    restart: always
    volumes:
      - workspace_vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${WORKSPACE_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${WORKSPACE_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${WORKSPACE_DB_NAME}
    ports:
      - 27517:27017
  model-db:
    image: mongo
    container_name: model-db
    restart: always
    volumes:
      - model_vol:/data/db
    ports:
      - 27518:27017
  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    volumes:
      - auth_vol:/data/db
    ports:
      - 27519:27017

  workspace:
    build: ./Workspace-Management
    container_name: workspace
    network_mode: host
    environment:
      - PORT=11140

      - DATABASE_IP=127.0.0.1
      - DATABASE_PORT=27517
      - DATABASE=${WORKSPACE_DB_NAME}
      - DATABASE_USER=${WORKSPACE_DB_USERNAME}
      - DATABASE_PASS=${WORKSPACE_DB_PASSWORD}

      - MODEL_MANAGEMENT_HOST=127.0.0.1
      - MODEL_MANAGEMENT_PORT=11150
      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

  model:
    build: ./Model-Management
    container_name: model
    network_mode: host
    environment:
      - LISTEN_IP=0.0.0.0
      - LISTEN_PORT=11150

      - DATABASE_NAME=${MODEL_DB_NAME}
      - DATABASE_PORT=27017
      - DATABASE_URI=mongodb://127.0.0.1:27518/

      - WORKSPACE_MANAGEMENT_IP_PORT=http://127.0.0.1:11140
      - AUTH_SECRET=${AUTHENTICATION_SECRET}

  auth:
    build: ./Authentication
    container_name: auth
    network_mode: host
    environment:
      - PORT=11160

      - DATABASE_IP=127.0.0.1
      - DATABASE_PORT=27519

      - ACCESS_TOKEN_SECRET=${AUTHENTICATION_SECRET}

      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  client:
    build: ./client
    container_name: client
    network_mode: host
    environment:
      - PORT=11170
    #   - BASE_URL=https://edge-ml.dmz.teco.edu/
